# Copyright © 2023 The Spray Proxy Contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprayproxy
  namespace: sprayproxy
  labels:
    app.kubernetes.io/name: sprayproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sprayproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sprayproxy
    spec:
      serviceAccountName: sprayproxy
      volumes:
        - name: tls
          secret:
            secretName: sprayproxy-tls
            defaultMode: 420
      containers:
        - name: sprayproxy
          image: ko://github.com/konflux-ci/sprayproxy
          args:
            - server
          env:
            - name: SPRAYPROXY_SERVER_BACKEND
            - name: GH_APP_WEBHOOK_SECRET
          ports:
            - containerPort: 8080
              name: server
          resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
        - name: kube-rbac-proxy
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--ignore-paths=/proxy,/healthz"
            - "--logtostderr=true"
            - "--v=4"
            - '--tls-cert-file=/etc/tls/tls.crt'
            - '--tls-private-key-file=/etc/tls/tls.key'
          ports:
            - containerPort: 8443
              protocol: TCP
              name: proxy
          volumeMounts:
            - name: tls
              readOnly: true
              mountPath: /etc/tls
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
        - name: kube-rbac-metrics
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
          args:
            - "--secure-listen-address=0.0.0.0:9443"
            - "--upstream=http://127.0.0.1:9090/"
            - "--logtostderr=true"
            - "--v=4"
          ports:
            - containerPort: 9443
              protocol: TCP
              name: metrics
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: sprayproxy
  labels:
    app.kubernetes.io/name: sprayproxy
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: sprayproxy-tls
spec:
  selector:
    app.kubernetes.io/name: sprayproxy
  ports:
    - name: proxy
      protocol: TCP
      port: 8443
      targetPort: proxy
---
# Two separate services are created as workaround for OCPBUGS-5916
kind: Service
apiVersion: v1
metadata:
  name: metrics
  labels:
    app.kubernetes.io/name: metrics
    app.kubernetes.io/part-of: sprayproxy
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9443
      targetPort: metrics
  selector:
    app.kubernetes.io/name: sprayproxy
